"""
Django settings for controle_precos project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import os
from pathlib import Path

NOTA_TITLE = [
    "DOCUMENTO AUXILIAR DA NOTA FISCAL DE CONSUMIDOR ELETRÔNICA",
    "DF-e Portal/Pr - Consulta DANFE NFC-e",
]

# A ordem dos regex importa
# especialmente para Unidades/Un e Leve x pague x
# x pode ser unidades, ml, g...
# se tirar eles antes vai sobrar um leve  pague  .
REGEX_LIST = [
    "[0-9]+ ?[uU]nidades?", "[0-9]+ ?[uU]{1}[nN]{1}", "[0-9]? ?[kK][gG]",
    "[0-9],[0-9]+ ?[kK][gG]", "[0-9]+\.[0-9]+ ?[gG]", "[0-9]+ ?[gG]",
    "[0-9]+ ?[mM][lL]", "[0-9]+ ?[lL]", "[0-9]+%",
    "Leve Mais Pague Menos" ,"Leve +Pague +", "Leve [0-9]+ Pague +",
    "Oferta|Especial|Desconto|Econômico|[eE]mbalagem"
    "[0-9]+ ?[sS]achês?", "[sS]achês?", "[0-9]+ C[aá]psulas?", 
    "[0-9]+ [rR]olos? ?", "[0-9]+ [mM]etros? ?",
    "[0-9]+ [rR]efis", "[rR]efil", "[0-9]+(cm)? ?x ?[0-9]+(cm)?"
]

CATEGORY_DICT = {
    1 : "Alimento",
    2 : "Bebida",
    3 : "Higiene",
    4 : "Limpeza",
    5 : "Outros",
}

TRAINING_SET = Path("/home/gustavo/Downloads/all_items_muffato.csv")

MODEL = ""

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-)aya(3iq0%^i0*+kayg*9k&e0g(j*(mg2!*!x-ceb2(b&$w#@o'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'notas_fiscais.apps.NotasFiscaisConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'controle_precos.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            os.path.join(BASE_DIR, 'notas_fiscais/templates')
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'controle_precos.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'pt-br'

TIME_ZONE = 'America/Sao_Paulo'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

STATICFILES_DIRS = [
    BASE_DIR / "notas_fiscais/static"
]

STATICFILES_ROOT = f'{BASE_DIR}/notas_fiscais/static/notas_fiscais/style.css'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
