# Generated by Django 5.2 on 2026-01-05 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notas_fiscais', '0002_itemnotafiscal_preco_unitario_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='codigo_barras',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='descricao',
        ),
    ]
