# Generated by Django 5.2 on 2026-01-06 02:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notas_fiscais', '0003_remove_produto_codigo_barras_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='supermercado',
            options={'verbose_name_plural': 'Supermercados'},
        ),
    ]
