# Generated by Django 5.2 on 2026-01-07 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notas_fiscais', '0004_alter_supermercado_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemnotafiscal',
            name='item_num',
            field=models.IntegerField(default=0, max_length=100),
        ),
    ]
