# Generated by Django 5.2 on 2026-01-08 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notas_fiscais', '0005_itemnotafiscal_item_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='notafiscal',
            name='total_items',
            field=models.IntegerField(default=1),
        ),
    ]
