# Generated by Django 5.2 on 2026-01-08 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notas_fiscais', '0006_notafiscal_total_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemnotafiscal',
            name='produto',
            field=models.CharField(max_length=50),
        ),
        migrations.DeleteModel(
            name='Produto',
        ),
    ]
