# Generated by Django 5.2 on 2026-01-08 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notas_fiscais', '0007_alter_itemnotafiscal_produto_delete_produto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemnotafiscal',
            name='item_num',
        ),
        migrations.RemoveField(
            model_name='notafiscal',
            name='numero',
        ),
    ]
