# Generated by Django 5.2 on 2026-01-08 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notas_fiscais', '0008_remove_itemnotafiscal_item_num_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notafiscal',
            options={'ordering': ['-data_emissao'], 'verbose_name_plural': 'Notas Fiscais'},
        ),
    ]
