# Generated by Django 5.2 on 2026-01-09 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notas_fiscais', '0009_alter_notafiscal_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemnotafiscal',
            options={'ordering': ['-nota_fiscal__data_emissao']},
        ),
    ]
