# Generated by Django 5.2 on 2026-01-13 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notas_fiscais', '0010_alter_itemnotafiscal_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='supermercado',
            options={},
        ),
    ]
