# Generated by Django 5.2 on 2026-01-13 13:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notas_fiscais', '0011_alter_supermercado_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemnotafiscal',
            name='categoria',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='notas_fiscais.categoriaproduto'),
        ),
    ]
