# Generated by Django 5.2 on 2026-01-13 13:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notas_fiscais', '0012_itemnotafiscal_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemnotafiscal',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='notas_fiscais.categoriaproduto'),
        ),
    ]
