# Generated by Django 5.2 on 2026-01-13 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notas_fiscais', '0013_alter_itemnotafiscal_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemnotafiscal',
            name='unidade_medida',
            field=models.CharField(choices=[('un', 'unidade'), ('kg', 'kilograma')], default='un', max_length=20),
        ),
    ]
