# Generated by Django 5.2 on 2026-01-13 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notas_fiscais', '0014_alter_itemnotafiscal_unidade_medida'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemnotafiscal',
            name='categoria',
            field=models.TextField(choices=[('alimento', 'Alimento'), ('bebida', 'Bebida'), ('higiene', 'Higiene'), ('limpeza', 'Limpeza'), ('outros', 'Outros')], default='outros'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='CategoriaProduto',
        ),
    ]
